DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos (
    id SERIAL NOT NULL,
    description CHARACTER VARYING NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    CONSTRAINT pkey_todos_id PRIMARY KEY (id)
);

ALTER TABLE todos DROP COLUMN IF EXISTS created_at;
ALTER TABLE todos DROP COLUMN IF EXISTS updated_at;
ALTER TABLE todos DROP COLUMN IF EXISTS deleted_at;